### PR TITLE
Add contributing.md

### PR DESCRIPTION
**Pull request by Smosker**

### CODE REVIEW

**Comment by Smosker** [comment]
@naohide Hello! We are moving library to another github organization with current licence, in order to do so we need to receive your (and all other conributors) agreement with text in contributing.md (see file in this PR). If you agreed with it, please, write about it..

**Comment by Smosker** [comment]
@confar  Hello! We are moving library to another github organization with current licence, in order to do so we need to receive your (and all other conributors) agreement with text in contributing.md (see file in this PR). If you agreed with it, please, write about it..

**Comment by naohide** [comment]
@Smosker I agree with you. cheers.

**Comment by Smosker** [comment]
@confar  please, see comment above

**Comment by Smosker** [comment]
@confar please, see comment above

**Comment by Smosker** [comment]
@confar please, see comment above

**Comment by Smosker** [comment]
@confar please, see comment above

**Comment by Smosker** [comment]
@confar please, see comment above

**Comment by Smosker** [comment]
@confar please, see comment above

**Pull request merged**
